### ISSUE TITLE
How to use zod string?

### ISSUE THREAD

**Issue by magick93** [StefanTerdell/json-schema-to-zod#53]
I've reviewed other posts on the same issue, but am unable to convert / eval the string zod schema.

- `const zod_schema = eval(parseSchema(schema)) ;` results in `ReferenceError: z is not defined` I also tried:

```
const import_z = 'import {  z } from "zod";'
const combined = import_z + parseSchema(schema);
```

This resulted in the same error.
- `const zod_schema = eval(jsonSchemaToZod(schema)) ;` results in `SyntaxError: Cannot use import statement outside a module`

**Comment by StefanTerdell** [comment]
Add `const { z } = require('zod')` or - for the billionth time - just use Ajv with the JSON schema instead of converting it

**Comment by finom** [comment]
> for the billionth time

@StefanTerdell the package name disinform everybody who's looking how to convert JSON to Zod. Programmatic example doesn't say anything about return type. What would somebody expect to get running the following code?

```ts
const schema = jsonSchemaToZod(myObject);
```

I would expect to return schema instead of a string. It would be fair to rename the project and update the example. Personally for me this confusion caused me to rethink completely what I was planning to do for 2 weeks and the fact that I noticed this undocumented issue just now costs me many hours of my time because I was naively relying on the documentation. Please, respect people who's going to use your thing.
