### ISSUE TITLE
Add an option to customize the parsing and output

### ISSUE THREAD

**Issue by rjmackay** [StefanTerdell/json-schema-to-zod#66]
It would be helpful to be able to customize parsing when needed, i.e. to allow coercing strings to numbers or other less standard behaviour.

My initial PR was reject but I'm happy to rework this if there's an interface you would be open to.
https://github.com/StefanTerdell/json-schema-to-zod/pull/39

**Comment by StefanTerdell** [comment]
Hi @rjmackay, try the parserOverride option. Looks like I forgot to document it :p

Return void if you dont want to customize the current node, otherwise return a json schema. If you like the interface Ill add it to the docs but I will await your feedback.

**Comment by apoteet** [comment]
@StefanTerdell LMK if you want a new issue for this discussion.  

This interface works for me. Documenting it would be handy since I only learned how to use the override option by finding this issue.
There seems to be a bug in the latest (and prior?) versions though, where if we set a parser override, the description is omitted where it was included before.
I hacked around this by having the parser override also set the description, but it's somehow inserting a newline when the description is long and causing syntax errors.

Here's a pared-down version of how i'm calling it:
```ts
jsonSchemaToZod(schema, {
    name: key,
    withoutDescribes: false,
    parserOverride: (schema) => {
      	if (schema.type === 'number') {
			let r = "z.coerce.number()";
			/* some other logic to add integer bounds */

			if (schema.description) {
			    r += `.describe('${schema.description}')`;
			}
			return r;
	    }
    },
}
```

With this example, the parser would return this. I added `|\n|` where it tries to put the newline
> z.coerce.number().lte(48).describe('Length (inches) of the package. Required if requesting a quote with a |\n|new order. The package volume (length * width * height) cannot exceed 4492.8 cubic inches (2.6 cubic feet).'
