### ISSUE TITLE
Please remove `fs` module from the dist

### ISSUE THREAD

**Issue by NWYLZW** [StefanTerdell/json-schema-to-zod#80]
When I use version `@2` in my project and pack it with webpack, the repository imports the `fs` module.

<img width="874" alt="image" src="https://github.com/StefanTerdell/json-schema-to-zod/assets/51358815/05c94436-8330-4f5b-96c2-f3edbd8bca4a">

However, the `fs` module is only supported for the `CLI` and is not necessary for common use cases.

**Comment by StefanTerdell** [comment]
I will not remove the function because it is crucial for the CLI to work and the use-case is a bad idea to begin with. Please see the last section of the readme.

Your options are to:
1. Fork the repo, remove the CLI parts, republish.
2. Create a PR that separates out the CLI parts in a reasonable manner, preferably without breaking changes.
3. Validate the JSON Schema you already have with a tool like AJV. This is the only reasonable option btw but you do you.

Good luck

**Comment by NWYLZW** [comment]
I will try the second option. Thanks for your reply.

**Comment by StefanTerdell** [comment]
@NWYLZW I think 2.0.14 may have solved your issue. WebPack should be able to ignore it now.

**Comment by NWYLZW** [comment]
Thank your work, I will try this version later
